from playwright.sync_api import Page, expect

# This was generated by the Playwright recorder tool called Codegen
def test_example(page: Page) -> None:
    page.goto("https://playwright.dev/")
    page.get_by_role("button", name="Node.js").click()
    page.get_by_label("Main", exact=True).get_by_role("link", name="Python").click()
    page.get_by_role("link", name="Get started").click()
    page.get_by_label("Switch between dark and light").click()
    page.get_by_label("Search").click()
    page.get_by_placeholder("Search docs").fill("codegen")
    page.get_by_placeholder("Search docs").press("Enter")